apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-flux
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott <pat@patscott.io>
    meta.crossplane.io/source: github.com/hops-ops/helm-flux
    meta.crossplane.io/description: Installs the Flux2 Helm chart with a minimal, stable interface.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.0.6"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
